[character]
# success_symbol = "[â””â¯](green)"
# success_symbol = "[â””^=|>](green)"
# success_symbol = "[~@|>](green)"
success_symbol = "[â¤·](bold green)"
# success_symbol = "[áŸš ](bold green)"

[python]
symbol = 'âš• '

[nodejs]
symbol = 'ğŸ›¼ '

[lua]
symbol = 'â˜¯ '

# âš• ~-ğŸ•‰ -~ â˜¸  âˆˆ Ïˆ Î¨ â¯â¯âˆˆ â§– ğ“‚€  â‡
# â†³ à¹›
