[character]
# success_symbol = "[â””â¯](green)"
# success_symbol = "[â””^=|>](green)"
# success_symbol = "[~@](green)"
success_symbol = "[~-ğŸ•‰ -~](green)"
# success_symbol = "[~ğŸ•‰ â¯âˆˆ](green)"
# success_symbol = "[â””ğŸ•‰ ğŸ‘](green)"

[python]
symbol = 'âš• '
# âš• ~ğŸ•‰ ~ â˜¸ ğŸ”± âˆˆ Ïˆ Î¨ â¯â¯âˆˆ â§– ğ“‚€

[nodejs]
symbol = 'ğŸ›¼ '

[lua]
symbol = 'â˜¯ '
